SMSWebsite/SMSWebsite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('smsApp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SMSWebsite/smsApp/urls.py
from django.urls import path
from .views import (SMSCreateView, SMSListView, SMSDetailView, ContactCreateView, ContactListView, ContactDetailView,
                    ContactUpdateView, ContactDeleteView, GroupCreateView, GroupListView, GroupDetailView,
                    GroupDeleteView)
from . import views

urlpatterns = [
    # path('', views.index, name='home'),
    path('', SMSCreateView.as_view(), name='sms-home'),
    path('sms/', SMSListView.as_view(), name='view-sms'),
    path('sms/<int:pk>/', SMSDetailView.as_view(), name='sms-detail'),
    path('ajax/load-contacts/', views.load_contacts, name='ajax_load_contacts'),
    path('contact/new/', ContactCreateView.as_view(), name='add-contact'),
    path('contact/', ContactListView.as_view(), name='view-contact'),
    path('contact/<int:pk>/', ContactDetailView.as_view(), name='contact-detail'),
    path('contact/<int:pk>/update/', ContactUpdateView.as_view(), name='update-contact'),
    path('contact/<int:pk>/delete/', ContactDeleteView.as_view(), name='delete-contact'),
    path('group/new/', GroupCreateView.as_view(), name='create-group'),
    path('group/', GroupListView.as_view(), name='view-group'),
    path('group/<int:pk>/', GroupDetailView.as_view(), name='group-detail'),
    path('group/<int:pk>/delete/', GroupDeleteView.as_view(), name='delete-group')
]

SMSWebsite/smsApp/models.py
from django.db import models
from django.urls import reverse


class RecipientGroup(models.Model):
    group_name = models.CharField(max_length=30, default='General contacts')

    def __str__(self):
        return self.group_name


class Recipient(models.Model):
    first_name = models.CharField(max_length=30, blank=False, null=False)
    last_name = models.CharField(max_length=30, blank=False, null=False)
    phone_number = models.CharField(max_length=13, blank=False, null=False)
    group_name = models.ForeignKey(RecipientGroup, default=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.phone_number

    def get_absolute_url(self):
        return reverse('sms-home')


class SMS(models.Model):
    phone_number = models.CharField(max_length=16)
    group_name = models.ForeignKey(RecipientGroup, on_delete=models.SET_NULL, null=True)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    cost = models.CharField(max_length=13, default='MWK 0.0000')
    status = models.CharField(max_length=10, blank=True, null=True)
    statusCode = models.IntegerField(blank=True, default=200)

    def __str__(self):
        return self.phone_number

SMSWebsite/smsApp/forms.py
from django import forms
from .models import SMS, Recipient, RecipientGroup


class ContactForm(forms.ModelForm):
    CHOICES = (
        ("csv", "CSV File"),
        ("contact", "Single Contact"),
    )

    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    phone_number = forms.CharField(max_length=13, min_length=10, required=False)
    entry_type = forms.ChoiceField(choices=CHOICES, required=False)

    class Meta:
        model = Recipient
        fields = ['entry_type', 'first_name', 'last_name', 'phone_number', 'group_name']


class SMSForm(forms.ModelForm):
    phone_number = forms.ModelChoiceField(queryset=None)
    group_name = forms.ModelChoiceField(queryset=RecipientGroup.objects.all())

    class Meta:
        model = SMS
        fields = ['group_name', 'phone_number', 'message']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone_number'].queryset = Recipient.objects.none()

        if 'group_name' in self.data:
            try:
                group_id = int(self.data.get('group_name'))
                self.fields['phone_number'].queryset = Recipient.objects.filter(group_name_id=group_id).order_by(
                    'phone_number')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['phone_number'].queryset = self.instance.group_name.phone_number_set.order_by('phone_number')

SMSWebsite/smsApp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from .models import SMS, Recipient, RecipientGroup
from .forms import ContactForm, SMSForm
from django.contrib import messages
from .sms import SendSMS
import re
import ast


def index(request):
    return render(request, 'smsApp/index.html')


class SMSListView(LoginRequiredMixin, ListView):
    model = SMS
    template_name = 'smsApp/sms_view.html'
    context_object_name = 'texts'
    ordering = ['-date']
    paginate_by = 4


class SMSDetailView(LoginRequiredMixin, DetailView):
    model = SMS


class SMSDeleteView(LoginRequiredMixin, UpdateView):
    model = SMS


class ContactListView(LoginRequiredMixin, ListView):
    model = Recipient
    template_name = 'smsApp/contact_view.html'
    context_object_name = 'contacts'


class ContactDetailView(LoginRequiredMixin, DetailView):
    model = Recipient
    template_name = 'smsApp/contact_detail.html'


class ContactUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipient
    fields = '__all__'
    template_name = 'smsApp/contact_form.html'


class ContactDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipient
    template_name = 'smsApp/contact_confirm_delete.html'
    success_url = reverse_lazy('view-contact')


def load_contacts(request):
    group_id = request.GET.get('group_name')
    contacts = Recipient.objects.filter(group_name_id=group_id).order_by('phone_number')
    return render(request, 'smsApp/include/contact_dropdown_list_options.html', {'contacts': contacts})


class SMSCreateView(LoginRequiredMixin, CreateView):
    model = SMS
    form_class = SMSForm
    # fields = ['phone_number', 'message']
    success_url = reverse_lazy('view-sms')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            phone_shell = [str(form.instance.phone_number).strip()]
            SendSMS.phone_number = phone_shell
            SendSMS.message = form.instance.message

            raw_response = SendSMS().send()

            try:
                raw_response_dict = re.findall("\[([^\[\]]*)\]", str(raw_response))
                message = ast.literal_eval(raw_response_dict[0])
                print(message)
                sms = SMS(phone_number=message['number'], message=form.instance.message, cost=message['cost'],
                          status=message['status'], statusCode=message['statusCode'])
                sms.save()
                messages.success(request, f"Message sent")
            except Exception as e:
                messages.error(request, f"Error: {raw_response} causing a ({e}) ERROR")

            return redirect('view-sms')

        else:
            phone_list = Recipient.objects.filter(group_name=form.instance.group_name)
            phone_shell = []
            for phone in phone_list:
                phone_shell.append(str(phone.phone_number).strip())
            SendSMS.phone_number = phone_shell
            SendSMS.message = form.instance.message

            raw_response = SendSMS().send()
            print(phone_shell)
            print("response: ", raw_response, " end")
            try:
                raw_response_dict = re.findall("\[(.*?)\]", str(raw_response))
                mod_line = str(raw_response_dict[0])
                size = len(mod_line)
                line = mod_line[:size - 1]
                delimiter = "}, "
                curl = "}"
                response_list = [e + curl for e in line.split(delimiter) if e]
                print(response_list)
                for data in response_list:
                    message = ast.literal_eval(data)
                    sms = SMS(phone_number=message['number'], message=form.instance.message, cost=message['cost'],
                              status=message['status'], statusCode=message['statusCode'])
                    sms.save()
                messages.success(request, f"Message sent to all contacts in {form.instance.group_name}")
            except Exception as e:
                messages.error(request, f"Error: {raw_response} as it causes( python {e}) ERROR")
                return redirect('sms-home')

            return redirect('view-sms')


class ContactCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = ContactForm
    template_name = 'smsApp/contact_form.html'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if len(request.FILES) != 0:
            files = request.FILES['file']
            if form.is_valid():
                try:
                    if str(files).endswith(".csv"):
                        file_data = files.read().decode("utf-8")
                        lines = file_data.split("\n")
                        for line in lines:
                            fields = line.split(",")
                            try:
                                if len(line) != 0:
                                    get_contacts = Recipient.objects.filter(phone_number=str(fields[2]).strip(),
                                                                            group_name=form.instance.group_name).exists()
                                    if get_contacts:
                                        messages.error(request,
                                                       f"{fields[2]} already exists in {form.instance.group_name}")
                                        continue
                                    contact = Recipient(
                                        first_name=fields[0], last_name=fields[1], phone_number=str(fields[2]).strip(),
                                        group_name=form.instance.group_name
                                    )
                                    contact.save()
                            except Exception as e:
                                messages.error(request, "Unable to add contacts " + repr(e))
                                pass
                        try:
                            if contact:
                                messages.success(request, f"Contacts added to {form.instance.group_name}")

                        except Exception as e:
                            print(e)
                    else:
                        messages.error(request, "Please Enter CSV")
                        redirect('add-contact')

                except Exception as e:
                    print(e)
                    messages.error(request, "Unable to upload file. " + repr(e))

                return redirect('add-contact')
            else:
                messages.error(request, "Error")
                return redirect('add-contact')
        else:
            if form.is_valid():
                get_contacts = Recipient.objects.filter(phone_number=form.instance.phone_number,
                                                        group_name=form.instance.group_name).exists()
                if get_contacts:
                    messages.error(request,
                                   f"{form.instance.phone_number} already exists in {form.instance.group_name}")
                    return redirect('add-contact')
                else:
                    messages.success(request, "Contact added")
                    return self.form_valid(form)
            else:
                return redirect('add-contact')


class GroupListView(LoginRequiredMixin, ListView):
    model = RecipientGroup
    template_name = 'smsApp/group_view.html'
    context_object_name = 'groups'


class GroupDetailView(LoginRequiredMixin, DetailView):
    model = RecipientGroup
    template_name = 'smsApp/group_detail.html'


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = RecipientGroup
    fields = '__all__'
    template_name = 'smsApp/group_form.html'
    success_url = reverse_lazy('view-group')


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = RecipientGroup
    template_name = 'smsApp/group_confirm_delete.html'
    success_url = reverse_lazy('view-group')
# Create your views here.

SMSWebsite/smsApp/templates/smsApp/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-info">

    <a class="navbar-brand" href="{% url 'sms-home' %}">SMS App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mx-auto">
            <!--<li class="nav-item active">
                <a class="nav-link" href="{% url 'sms-home' %}">Home <span class="sr-only">(current)</span></a>
            </li>-->
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item ">
                <a href="{% url 'profile' %}">
                    <img class="rounded-circle" src="{{ user.profile.image.url }}" width="32" height="32">
                </a>
            </li>
            <li class="nav-item ">
                <a class="nav-link float-right text-white" href="{% url 'profile' %}">{{ user.username }}</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link float-right text-white" href="{% url 'logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item ">
                <a class="nav-link float-right text-white" href="{% url 'login' %}">Log in</a>
            </li>
            <!--<li class="nav-item ">
                <a class="nav-link float-right " href="{% url 'register' %}">Register</a>
            </li>-->
            {% endif %}
        </ul>

    </div>
</nav>

<div class="container" style="padding-top:80px;">
    <div class="row">
        {% if user.is_authenticated %}
        {% with active_view=request.resolver_match.url_name %}
        <div class="col-sm-3">
            <div class="list-group">
                <a href="{% url 'sms-home' %}"
                   class="list-group-item list-group-item-action  {% if active_view == 'sms-home'%}
                   bg-info text-white{% endif %}">
                    Send SMS
                </a>
                <a
                        href="{% url 'add-contact' %}"
                        class="list-group-item list-group-item-action  {% if active_view == 'add-contact'%}
                   bg-info text-white{% endif %}">
                    Add Contacts
                </a>
                <a href="{% url 'view-contact' %}"
                   class="list-group-item list-group-item-action  {% if active_view == 'view-contact'%}
                   bg-info text-white{% endif %}">
                    Manage Contacts
                </a>
                <a
                        href="{% url 'view-group' %}"
                        class="list-group-item list-group-item-action  {% if active_view == 'view-group'%}
                   bg-info text-white{% endif %}">
                    Manage Groups
                </a>
                <a href="{% url 'view-sms' %}"
                   class="list-group-item list-group-item-action  {% if active_view == 'view-sms'%}
                   bg-info text-white{% endif %}">
                    Manage SMS
                </a>
            </div>
        </div>
        {% endwith %}
        {% endif %}
        <div class="{%if request.resolver_match.url_name == 'login' %}col-sm-5 mx-auto {% else %}col-sm-9{% endif %} ">
            <div class="container">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert"
                ">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
    </div>
</div>


</div>


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>
{% block script %}{% endblock %}

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
-->
</body>
</html>

SMSWebsite/smsApp/templates/smsApp/contact_confirm_delete.html
{% extends 'smsApp/base.html' %}
{% block tittle %} Delete Contact {% endblock %}
{% block content %}
<div class="container">

    <div class="row">

        <div class="col-sm-12">
            <form action="" method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">
                        Delete {{ object.first_name}} {{object.last_name}} ({{object.phone_number}})
                    </legend>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-danger" type="submit">
                        Yes, Delete
                    </button>
                    <a class="btn btn-secondary" href="{% url 'contact-detail' object.id%}">
                        Cancel
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

SMSWebsite/smsApp/templates/smsApp/contact_detail.html
{% extends 'smsApp/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Contact Details {% endblock %}
{% block content %}
<div class="container">


    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Number</th>
                    <th scope="col">Group</th>
                    <th scope="col"></th>

                </tr>
                </thead>
                <tbody>

                <tr class="clickable-row table-row" data-href-template="#"
                    onclick="window.location.assign('#'">

                    <td>{{ object.first_name }}</td>
                    <td>{{ object.last_name }}</td>
                    <td>{{ object.phone_number }}</td>
                    <td>{{ object.group_name }}</td>
                    <td>
                        <a href="{% url 'delete-contact' object.id %}">
                           <i class="fa fa-trash" style="font-size:24px;color:gray;"></i>
                        </a>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>

    </div>


</div>


{% endblock %}

SMSWebsite/smsApp/templates/smsApp/contact_form.html
{% extends 'smsApp/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Add Contacts {% endblock %}
{% block content %}
<div class="container">

    <div class="row">

        <div class="col-sm-12">
            <h1 class='text-left'>Add Contact</h1>
            <div class="form-group">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form|crispy }}

                        <div id="div_id_CSV_file" class="input-group mb-3">
                            <div class="custom-file">
                                <input type="file" name="file" class="custom-file-input" id="id_CSV_file"
                                aria-describedby="inputGroupFileAddon01">
                                <label class="custom-file-label" for="id_CSV_file">Choose file</label>
                            </div>
                        </div>
            </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-info" type="submit">
                    Add
                </button>
            </div>
            </form>

        </div>


    </div>
</div>
</div>

{% endblock %}


{% block script %}
<script>
// Add the following code if you want the name of the file appear on select
$( document ).ready(function() {
    $("#div_id_first_name").attr("hidden",true).removeClass("requiredField");
    $("#id_first_name").prop("required",false).attr("disabled",true);

    $("#div_id_last_name").attr("hidden",true).removeClass("requiredField");
    $("#id_last_name").prop("required",false).attr("disabled",true);

    $("#div_id_phone_number").attr("hidden",true).removeClass("requiredField");
    $("#id_phone_number").prop("required",false).attr("disabled",true);

    $("#div_id_CSV_file").attr("hidden",false);
    $("#id_CSV_file").attr("required",true);

});

$('#id_entry_type').change(function(){
  if($(this).val() == 'csv'){
    $("#div_id_first_name").attr("hidden",true).removeClass("requiredField");
    $("#id_first_name").prop("required",false).attr("disabled",true);

    $("#div_id_last_name").attr("hidden",true).removeClass("requiredField");
    $("#id_last_name").prop("required",false).attr("disabled",true);

    $("#div_id_phone_number").attr("hidden",true).removeClass("requiredField");
    $("#id_phone_number").prop("required",false).attr("disabled",true);

    $("#div_id_CSV_file").attr("hidden",false);
    $("#id_CSV_file").attr("required",true);
  }
  else{
    $("#div_id_first_name").attr("hidden",false).addClass("requiredField");
    $("#id_first_name").prop("required",true).attr("disabled",false);

    $("#div_id_last_name").attr("hidden",false).attr("required",true).addClass("requiredField");
    $("#id_last_name").prop("required",true).attr("disabled",false);

    $("#div_id_phone_number").attr("hidden",false).attr("required",true).addClass("requiredField");
    $("#id_phone_number").prop("required",true).attr("disabled",false);

    $("#div_id_CSV_file").attr("hidden",true);
    $("#id_CSV_file").attr("required",false);
  }
});

$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>
{% endblock %}

SMSWebsite/smsApp/templates/smsApp/contact_view.html
{% extends 'smsApp/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Contacts {% endblock %}
{% block content %}
<div class="container">


    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Number</th>
                    <th scope="col">Group</th>
                </tr>
                </thead>
                <tbody>
                {% for contact in contacts %}
                <tr class="clickable-row table-row" data-href-template="#"
                    onclick="window.location.assign('{% url 'contact-detail' contact.id %}');">
                    <th scope="row">{{ contact.id }}</th>
                    <td>{{ contact.first_name }}</td>
                    <td>{{ contact.last_name }}</td>
                    <td>{{ contact.phone_number }}</td>
                    <td>{{ contact.group_name }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

    </div>


</div>


{% endblock %}

SMSWebsite/smsApp/templates/smsApp/group_confirm_delete.html
{% extends 'smsApp/base.html' %}
{% block tittle %} Delete Group {% endblock %}
{% block content %}
<div class="container">

    <div class="row">

        <div class="col-sm-12">
            <form action="" method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Delete {{object.group_name}} Group</legend>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-danger" type="submit">
                        Yes, Delete
                    </button>
                    <a class="btn btn-secondary" href="{% url 'group-detail' object.id%}">
                        Cancel
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

SMSWebsite/smsApp/templates/smsApp/group_detail.html
{% extends 'smsApp/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Group Details {% endblock %}
{% block content %}
<div class="container">


    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover ">
                <thead>
                <tr>

                    <th colspan="5" scope="colgroup" class="text-center h1 border-top-0">
                        <span class="float-right ">
                            <a href="{% url 'delete-group' object.id %}">
                        <i class="fa fa-trash" style="font-size:24px;color:gray;z-index:-1"></i>
                            </a>
                        </span>
                        {{ object.group_name }}
                        <span>
                            <a href="{% url 'add-contact' %}">
                           <i class="fa fa-plus" style="font-size:24px;color:gray;"></i>
                            </a>
                        </span>
                    </th>

                </tr>


                </thead>
                <tbody>
                {% if object.recipient_set.all %}
                {% for contact in object.recipient_set.all %}
                <tr class="clickable-row table-row" data-href-template="#"
                    onclick="window.location.assign('{% url 'contact-detail' contact.id %}');">
                    <th scope="row">{{ contact.id }}</th>
                    <td>{{ contact.first_name }}</td>
                    <td>{{ contact.last_name }}</td>
                    <td>{{ contact.phone_number }}</td>
                    <td>{{ contact.group_name }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="5" scope="colgroup" class="text-center text-muted">EMPTY</td>
                </tr>
                {% endif %}


                </tbody>
            </table>
        </div>

    </div>


</div>


{% endblock %}

SMSWebsite/smsApp/templates/smsApp/index.html
{% extends 'smsApp/base.html' %}
{% block tittle %} SMS App {% endblock %}
{% block content %}
    <h3>Form</h3>
<form action="" method="post">
    {%csrf_token%}
    {{form}}
</form>

{% endblock %}

SMSWebsite/smsApp/templates/smsApp/sms_form.html
{% extends 'smsApp/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create SMS {% endblock %}
{% block content %}
<div class="container">

    <div class="row">

        <div class="col-sm-12">
            <h1 class='text-left'>Create SMS</h1>
            <!--<div class="input-group mb-3">
                <select class="custom-select" id="id_group_list">
                    {%for group in groups %}
                    <option value="{{group.id}}">{{group.group_name}}</option>
                    {% endfor %}
                </select>
            </div>-->
            <form id="smsForm" method="post" data-contacts-url="{% url 'ajax_load_contacts' %}" novalidate>
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-info" type="submit">
                        Send
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

{% block script %}
<script>
    $("#id_group_name").change(function () {
      var url = $("#smsForm").attr("data-contacts-url");  // get the url of the `load_cities` view
      var contactId = $(this).val();  // get the selected country ID from the HTML input


      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'group_name': contactId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_phone_number").html(data);  // replace the contents of the city input with the data that came from the server
          var array = []
          $('#id_phone_number option').each(function(index){
            array.push(index)
          });
          if (array.length == 1){
            $("#id_phone_number").html('<option value="all">Empty group</option>')
          }
        }
      });

    });
</script>
{% endblock %}